/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/NDD2sZtGNFF
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    (<div className="flex w-full max-w-sm items-center space-x-2">
      <div className="grid grid-cols-2 gap-4 w-full">
        <div className="space-y-2">
          <Label htmlFor="player-name">Player Name</Label>
          <Input id="player-name" placeholder="Enter player name" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="player-tag">Player Tag</Label>
          <Input id="player-tag" placeholder="Enter player tag" />
        </div>
      </div>
      <Button type="submit">
        <svg
          className=" text-white"
          fill="none"
          height="24"
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="2"
          viewBox="0 0 24 24"
          width="24"
          xmlns="http://www.w3.org/2000/svg">
          <circle cx="11" cy="11" r="8" />
          <path d="m21 21-4.3-4.3" />
        </svg>
      </Button>
    </div>)
  );
}
